name: Post Marketing Tweet
on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch: # Adds manual trigger option
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST https://tf-lock-alert-bot.vercel.app/api/twitter-marketing
