name: Post Marketing Tweet
on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl to post marketing tweet
        env:
          BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          echo "Making request with token length: ${#BEARER_TOKEN}"
          curl -v -X POST \
            -H "Authorization: Bearer $BEARER_TOKEN" \
            -H "Content-Type: application/json" \
            https://tf-lock-alert-bot.vercel.app/api/twitter-marketing
